swagger: '2.0'
info:
  description: |
    API Adquirencia
    
    ## Limitaciones
    - Sólo tarjetas de crédito Mastercard
    - Sin cuotas
    - Sin captura diferida
    - Todos los montos deben estar en pesos chilenos (ISO 4217 = `152`)
    - La API no soporta CORS
    
    ## Reglas de la API
    - Todos los métodos son idempotentes y, por lo tanto, pueden ser reintentados
    - El campo `consumer_transaction_id` debe ser único (incluso en días y transacciones distintas) 
    - Cuando Multicaja recibe por enésima vez una transacción (`consumer_transaction_id` repetido), retornará el resultado de la primera vez que la realizó
    
    ## Pendientes
    - Agregar autenticación con `api_key` o similar
    - Agregar operación de devolución.
  version: '0.1'
  title: API Adquirencia
host: 'api.multicaja.cl'
basePath: /adquirencia/v0.1/
consumes:
  - application/json
produces:
  - application/json
paths:

  /charge:
    post:
      summary: Venta con tarjeta
      description: |
        Realiza un cargo en una tarjeta de crédito Mastercard.
      parameters:
        - in: body
          name: charge_new
          description: Venta con tarjeta
          required: true
          schema:
            $ref: '#/definitions/charge_new'
      responses:
        '200':
          description: |
            OK - Venta exitosa
          schema:
            $ref: '#/definitions/charge'
        '400':
          description: Error en parámetros, se lanza a cuando un parámetro es requerido y no se ha enviado
          schema:
            $ref: '#/definitions/error_obj'
        '401':
          description: API Key no autorizada
          schema:
            $ref: '#/definitions/error_obj'
        '402':
          description: Transacción se intentó, pero falló.
          schema:
            $ref: '#/definitions/error_obj'
        '500':
          description: Error indeterminado, se lanza cuando ocurre un error imprevisto de sistema
          schema:
            $ref: '#/definitions/error_obj'
  /charge/reversal:
    post:
      summary: Reversa de venta con tarjeta
      description: |
        Devuelve la totalidad del monto cobrado a través de una compra.
        
      parameters:
        - in: body
          name: charge_new
          description: Reversa de venta con tarjeta
          required: true
          schema:
            $ref: '#/definitions/reversal_new'
      responses:
        '200':
          description: |
            OK - Reversa exitosa
          schema:
            $ref: '#/definitions/reversal'
        '400':
          description: Error en parámetros, se lanza a cuando un parámetro es requerido y no se ha enviado
          schema:
            $ref: '#/definitions/error_obj'
        '401':
          description: API Key no autorizada
          schema:
            $ref: '#/definitions/error_obj'
        '500':
          description: Error indeterminado, se lanza cuando ocurre un error imprevisto de sistema
          schema:
            $ref: '#/definitions/error_obj'

definitions:

  reversal_new:
    type: object
    description: |
      Solicitud de reversa de venta **(Request)**
    required:
      - consumer_transaction_id
    properties:
      consumer_transaction_id:
        type: string
        description: Identificador único de la transacción generado por el consumidor de la API
        example: "9cf7f55"
        
  reversal:
    type: object
    description: |
      Respuesta a solicitud de reversa de venta **(Response)**
    allOf:
      - $ref: "#/definitions/reversal_new"
      - type: object
        required:
          - process_date
        properties:
          original_transaction_status:
            type: string
            enum: ["approved-reconciled", "approved-not-reconciled", "failed", "non-existent"]
            description: |
             Estado de la transacción original

              * 'approved-reconciled': La transacción original estaba aprobada y conciliada con la bandera. Consulte los campos `original_transaction_codigo_mc`, `original_transaction_external_authorization_code` y `original_transaction_process_date`. (La transacción original será reversada)
              * 'approved-not-reconciled': La transacción original estaba aprobada y *no* conciliada con la bandera. Consulte los campos `original_transaction_codigo_mc`, `original_transaction_external_authorization_code` y `original_transaction_process_date`. (La transacción original será reversada)
              * 'failed': La transacción original existe, pero fue rechazada. Esta llamada no ha tenido efecto.
              * 'non-existent': La transacción original no existe. Esta llamada no ha tenido efecto.
          original_transaction_multicaja_id:
            type: integer
            description: Código identificador de la transacción original reversada. Si este campo viene vacío, significa que Multicaja no recibió la transacción original
            example: 7783834
          original_transaction_external_authorization_code:
            type: integer
            description: Identificador único de la transacción original reversada en el switch de la bandera
            example: 1231232
          original_transaction_process_date:
            type: string
            format: date-time
            description: Fecha en la que la transacción original hubiera sido o fue conciliada con la bandera, en formato ISO 8601
            example: "2018-01-14"

  charge_base:
    type: object
    description: |
      Contenido mínimo de una venta con tarjeta
    properties:
      amount:
        $ref: "#/definitions/amount_and_currency_new"
      consumer_transaction_id:
        type: string
        description: Identificador único de la transacción generado por el consumidor de la API
        example: "9cf7f55"
        
  charge_new:
    type: object
    description: |
      Solicitud de venta **(Request)**
    allOf:
      - $ref: "#/definitions/charge_base"
      - type: object
        required:
          - card
          - amount
          - consumer_transaction_id
          - merchant_code
        properties:
          card:
            $ref: "#/definitions/card_new"
          merchant_code:
            type: string
            description: Código de comercio asociado a la compra
            example: "0023434"
          merchant_descriptor:
            type: string
            description: Nombre del comercio. Máximo 6 caracteres.
            example: "PAYPAL"

  charge:
    type: object
    description: |
      Respuesta a solicitud de venta **(Response)**
    allOf:
      - $ref: "#/definitions/charge_base"
      - type: object
        required:
          - codigo_mc
          - external_authorization_code
          - process_date
          - timestamps
        properties:
          multicaja_id:
            type: integer
            description: Código identificador de la compra en los sistemas de Multicaja
            example: 7783834
          external_authorization_code:
            type: integer
            description: Identificador único de la transacción en el switch de la bandera
            example: 1231232
          process_date:
            type: string
            format: date-time
            description: Fecha en la que la transacción será conciliada con la bandera, en formato ISO 8601
            example: "2018-01-14"
          timestamps:
            $ref: '#/definitions/timestamps'
  timestamps:
    type: object
    description: |
      Fecha de creación y de última modificación **(Response)**
    properties:
      created_at:
        type: string
        format: date-time
        example: "2018-01-14T15:27:42.669Z"
      updated_at:
        type: string
        format: date-time
        example: "2018-03-02T10:03:12.123Z"

  amount_and_currency_new:
    type: object
    description: Monto en una moneda específica
    required:
      - currency_code
      - value
    properties:
      currency_code:
        type: integer
        description: Código ISO 4217 (numeric) de la moneda
        example: 152
      value:
        type: number
        description: Monto en formato decimal
        example: "1000.00"

  error_obj:
    type: object
    description: Error
    required:
      - code
    properties:
      code:
        type: string
        format: int32
        description: Código que representa el error. No será igual al código HTTP.
        example: "Mastercard0098234892"
      message:
        type: string
        description: Descripción corta del error
        example: "La tarjeta no tiene saldo"

  card_new:
    type: object
    description: |
      Información de la tarjeta prepago
    required:
      - exp_month
      - exp_year
      - pan
    properties:
      exp_month:
        type: integer
        description: mes de expiración
        example: 9
      exp_year:
        type: integer
        description: año de expiración
        example: 2020
      cvc:
        type: integer
        description: código de seguridad
        example: 123
      pan:
        type: string
        description: PAN de la tarjeta
        example: "1234123412341234"
      name_on_card:
        type: string
        description: Nombre impreso en la tarjeta
        example: "Pedro Perez"
