swagger: '2.0'
info:
  description:  |
    Bienvenido a la API de [Multicaja](https://www.multicaja.cl)
    Todos los requests son autenticados usando el header http `apikey`.
  version: "1.0.0"
  title: API de Pagos de Multicaja
    
host: api.staging.multicajapagosdigitales.cloud

consumes:
  - application/json
produces:
  - application/json
  
tags:
- name: transaccional
  description: Opciones de la  Orden

paths:
  /payment-gateway/v1/orders:
    post:
      tags:
      - transaccional
      summary: Generar una order (Intención de pago)
      description: |
        Servicio para poder crear una intención de pago.
        Algunos atributos de la orden enviada como parámetro: 
        * **reference_id**: `ID` interno del comercio (debe ser único).
        * **user**: Lista con propiedades del usuario.
          * Ejemplo: `{ "email": "example@multicaja.cl", "rut": "111111111" }"`
        * **amount** : Lista con propiedades de montos a pagar.
          * **currency**: Tipo de modeda.
            * Ejemplo: `"CLP"`
          * **total**: Total a pagar incluyendo impuestos.
          * **details**: Lista con propiedades de detalles de montos de pago.
            * **subtotal**: Suma total monto de items antes de impuestos.
            * **fee**: Comisión aplicado al subtotal.
            * **tax**: Impuesto aplicado al subtotal.
        * **methods** : Lista con textos de medios de pago habilitados, utilizando caracter asterisco para considerar todos los medios de pago.
          * Ejemplos:
            * Con botonera de Multicaja: `[ "efectivo", "transferencia", "paypal", "tarjetas" ]`
            * Api efectivo: `[ "efectivo_api" ]`
            * Api transferencia: `[ "transferencia_api" ]`
            * Todos los medios de pago: `[ "*" ]`
        * **items**: Lista con propiedades de productos/servicios a adquirir. Son opcionales y dependen del negocio.
          * **name**: Nombre.
          * **code**: Código.
          * **price**: Suma del precio total de unidades del producto.
          * **unitPrice**: Precio unitario.
          * **quantity**: Cantidad de productos.
        * **description**: Descripción de la orden.
        * **customs**: lista de propiedades llave/valor necesarios para ejecutar un webhook.
          * **key**: Identificador de propiedad.
          * **value**: Valor de propidad.
          * Ejemplos:
            * Para pago de tarjeta bip: `[ { "key": "cardId", "value": "123456" }, { "key": "validationType", "value": "1" } ]`
            * Para pago por método efectivo o efectivo_api: `[ { "key": "commerce_id", "value": "12345" }, {"key": "branch_id", { "value": "1234" }, { "key": "request_duration", "value": "60" }, {"key": "notify_user", { "value": "true" } ]`
        * **urls** : Url de redirección para los casos de éxito y error.
          * **return_url**: URL de retorno a página de e-commerce en caso de una compra exitosa.
          * **cancel_url**: URL de retorno a página de e-commerce en caso de una compra fallida.
          * **logo_url**: URL del logo del e-commerce, se presentará en un espacio de 80x80 pixeles.
        * **webhooks** : APIs REST `opcionales` requeridas para informar al comercio, deben atender por `POST`
          * **webhook_validation**: Ejecutado en la creación de una orden (Permite validar una orden antes de ser creada).
          * **webhook_confirm**: Ejecutado cuando una orden ha sido pagada exitosamente.
          * **webhook_reject**: Ejecutado cuando una orden ha fallado en el proceso de pago.

        Atributos agregados a la respuesta dinamicamente según el medio de pago solicitado:
          
        - Para método de pago `efectivo_api`, se retornará una estructura con el cupón: "payment_details":[{"key":"mc_order_id","value":"1555530269241"},{"key":"coupon_code","value":"123456789"},{"key":"expiration_date","value":"2019-04-17T19:44:29.241Z"},{"key":"map_url","value":"https://www.multicaja.cl/puntos-de-pago-efectivo/?monto=menor"}]

      parameters:
        - in: header
          name: apikey
          type: string
          required: true
        - in: body
          required: true
          name: body
          description: Parametros de entrada para el micomercio
          schema:
            $ref: '#/definitions/OrderModel'
      responses:
        201:
          description: Orden creada con éxito
          schema:
            $ref: '#/definitions/OrderModelResponse'
        400:
          description: Parametros de entrada incorrectos
          schema:
            $ref: '#/definitions/ErrorModel'
        403: 
          description: Prohibido continuar
          schema:
            $ref: '#/definitions/ErrorModel'
        500: 
          description: Error interno en procesamiento
          schema:
            $ref: '#/definitions/ErrorModel'
        502: 
          description: Error en respuesta de servicio
          schema:
            $ref: '#/definitions/ErrorModel'

  /payment-gateway/v1/orders/{order_id}:
    get:
      tags:
      - transaccional
      summary: Obtener el estado de la orden
      description: Servicio para poder obtener detalles de la orden y su estado actual.      
      parameters:
        - in: header
          name: apikey
          type: string
          required: true
        - in: path
          name: order_id
          description: Id de la orden de Multicaja
          required: true
          type: string
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/OrderModelResponse'
        400:
          description: Parametros de entrada incorrectos
          schema:
            $ref: '#/definitions/ErrorModel'
        403: 
          description: Prohibido continuar
          schema:
            $ref: '#/definitions/ErrorModel'
        404:
          description: Error obtención de datos
        500: 
          description: Error interno en procesamiento
          schema:
            $ref: '#/definitions/ErrorModel'
        502: 
          description: Error en respuesta de servicio
          schema:
            $ref: '#/definitions/ErrorModel'

    delete:
      tags:
        - transaccional
      summary: Cancelar la orden
      description: Este servicio permite anular orden.      
      parameters:
        - in: header
          name: apikey
          type: string
          required: true
        - in: path
          name: order_id
          description: Id de la orden de Multicaja
          required: true
          type: string
      responses:
        200:
          description: ok
        400:
          description: Parametros de entrada incorrectos
          schema:
            $ref: '#/definitions/ErrorModel'
        410:
          description: La intención de pago fue anulada.
          schema:
            $ref: '#/definitions/ErrorModel'
        404:
          description: error orden no existe

definitions:

  UserModel:
    type: object
    properties:
      email:
        type: string
        example: "example@multicaja.cl"
      rut:
        type: string
        example: "111111111"
  
  OrderModel:
    type: object
    required:
    - reference_id
    - amount
    - description
    - methods
    properties:
      reference_id:
        type: string
        example: "ERWER213"
        maximum: 30
      user:
        $ref: '#/definitions/UserModel'
      amount:
        $ref: '#/definitions/AmountModel'
      methods:
        type: array
        example: ['paypal', 'tarjetas', 'efectivo', 'efectivo_api']
        items:
          type: string
          example: "efectivo"
      items:
        type: array
        items:
          $ref: '#/definitions/ItemModel'
      description:
        type: string
        example: Esta es una orden
        maximum: 300
      customs:
        type: array
        items:
          $ref: '#/definitions/CustomModel'
      urls:
        $ref: '#/definitions/UrlModel'
      webhooks:
        $ref: '#/definitions/WebhookModel'

  OrderModelResponse:
    allOf:
      - $ref: '#/definitions/OrderModel'
      - properties:
          status:
            type: string
            enum: ['pending', 'canceled', 'completed','expired']
            example: "pending"
          order_id:
            type: string
            example: 64568939346Xabc2
          redirect_url:
            type: string
            example: 'http://pagos.multicaja.cl/url_retorno'
            maximum: 300
          merchant:
            type: object
            properties:
              rut:
                type: string
                example: "1-9"
              business_name:
                type: string
                example: "Company LLC."
              brand_name:
                type: string
                example: "Pop Company"
          payment_details:
            type: array
            items:
              $ref: '#/definitions/CustomModel'
              
  AmountModel:
    type: object
    properties:
      currency:
        type: string
        example: "CLP"
      total:
        type: number
        example: 41000
      details:
        type: object
        properties:
          subtotal:
            type: number
            example: 39000
          fee:
            type: number
            example: 1000
          tax:
            type: number
            example: 1000
            
  CustomModel:
    type: object
    required:
      - key 
      - value
    properties:
      key:
        type: string
        example: "atributo"
        maximum: 500
      value:
        type: string
        example: "valor del atributo"
        maximum: 500

  ItemModel: 
    type: object
    properties:
      name:
        type: string
        example: "name"
        maximum: 150
      code:
        type: string
        example: "code"
        maximum: 64
      price:
        type: number
        example: 39000
      unit_price:
        type: number
        example: 13000
      quantity:
        type: number
        example: 3

  UrlModel:
    type: object
    required:
      - return_url 
      - cancel_url
    properties:
      return_url:
        type: string
        example: "https://www.micomercio.cl/return_url"
        maximum: 300
      cancel_url:
        type: string
        example: "https://www.micomercio.cl/cancel_url"
        maximum: 300
      logo_url:
        type: string
        example: "https://www.micomercio.cl/logo.jpg"
        maximum: 300
          
  WebhookModel:
    type: object
    properties:
      webhook_validation:
        type: string
        example: "https://www.micomercio.cl/validation"
        maximum: 300
      webhook_confirm:
        type: string
        example: "https://www.micomercio.cl/confirm"
        maximum: 300
      webhook_reject:
        type: string
        example: "https://www.micomercio.cl/reject"
        maximum: 300

  ErrorModel:
    type: object
    properties:
      code: 
        type: string
        example: ERROR_CODE
        description: Variable de error
      message:
        type: string
        example: '{error_message}'
        description: Descripción del error
