swagger: '2.0'
info:
  description:  |
    Bienvenido a la API de [Multicaja](https://www.multicaja.cl) (Alpha)
    ** Este es un proyecto alpha y por lo tanto sufrirá muchos cambios **
    Todos los requests son autenticados usando un `api-key`.
    Existen dos ambientes: `qa` y `producción`. El `host` de `qa` es `apiqa.multicaja.cl`.
  version: "1.0.0"
  title: API Multicaja BDP-REST
  # put the contact info for your development or API team
  contact:
    email: matias.salinas@multicaja.cl
    
# Added by API Auto Mocking Plugin
# host: 'api.multicaja.cl'
# basePath: /v0.1-alpha/
consumes:
  - application/json
produces:
  - application/json
  
# tags are used for organizing operations
tags:
- name: transaccional
  description: Comunicación ecommerce
- name: efectivo
  description: Información efecitvo
- name: transferencia
  description: Información transferencia
- name: general
  description: Información transversal de todos los medios de pago
- name: encuesta
  description: Encuesta de anulaciones

paths:
  /pdp/order:
    post:
      tags:
      - transaccional
      summary: Generar nuevo pedido para el comercio ***(Público)***
      description: |
        Servicio para poder crear un nuevo pedido y el cual retornara la información de la orden.
      parameters:
      - in: body
        required: true
        name: body
        description: Parametros de entrada para el comercio
        schema:
          $ref: '#/definitions/orderInput'
      consumes:
      - application/json    
      produces:
      - application/json
      responses:
        201:
          description: Pedido creado
          schema:
            $ref: '#/definitions/orderStatus'
        400:
          description: Parametros de entrada incorrectos
          schema:
            $ref: '#/definitions/ErrorResponse'
  /pdp/order/{order_id}:
    get:
      tags:
      - transaccional
      description: |
        Servicio para poder obtener detalles del pedido y su estado actual
      summary: Obtener el estado del pedido  ***(Público)***
      operationId: addInventory
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: path
          name: order_id
          description: ID de orden de boton de pago
          required: true
          type: number
      responses:
        201:
          description: ok
          schema:
            $ref: '#/definitions/orderStatus'
        400:
          description: Parametros de entrada incorrectos
          schema:
            $ref: '#/definitions/ErrorResponse'
        403:
          description: El pedido fue anulado.
          schema:
            $ref: '#/definitions/OrderCanceled'
        404:
          description: error obtención de datos
    put:
      tags:
      - transaccional
      summary: Actualizar el pedido  ***(Interno)***
      description: |
        Servicio para actualizar datos del pedido, solo permite 
          - ID interno del ecommmerce ec_order_id.
          - Dirección de correo del comprador.
          - RUT del comprado
          - Descripción de la compra.
      parameters:
        - in: path
          name: order_id
          description: ID de pedido de boton de pago
          required: true
          type: number
        - in: body
          required: true
          name: body
          description: Parametros de entrada para el comercio
          schema:
            $ref: '#/definitions/orderUpdate'
      consumes:
      - application/json    
      produces:
      - application/json
      responses:
        201:
          description: Pedido creado
          schema:
            $ref: '#/definitions/orderStatus'
        400:
          description: Parametros de entrada incorrectos
          schema:
            $ref: '#/definitions/ErrorResponse'
      
    delete:
      tags:
      - transaccional
      summary: Cancelar el pedido  ***(Público)***
      description: |
        Este servicio permite anular un pedido.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: path
          name: order_id
          description: id de orden de boton de pago
          required: true
          type: number
      responses:
        201:
          description: ok
        400:
          description: Parametros de entrada incorrectos
          schema:
            $ref: '#/definitions/ErrorResponse'
        410:
          description: El pedido fue anulado.
          schema:
            $ref: '#/definitions/OrderCanceled'
        404:
          description: error el pedido no existe
  /pdp/order/{order_id}/cash: 
    post:
      tags:
      - efectivo
      summary: Generar pago en efectivo  ***(Público)***
      description: |
        Este servicio genera el pago de un pedido en efectivo.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: path
          name : order_id
          type: integer
          required: true
          description: Id de orden
        - in: body
          name: body
          required: true
          description: parametros para generar un pago efectivo
          schema:
            $ref: '#/definitions/cashInit'
      responses:
        201:
          description: ok
          schema:
            type: object
            properties:
              sequence_code:
                type: string
                example: 4684545456
        400:
          description: Parametros de entrada incorrectos
          schema:
            $ref: '#/definitions/ErrorResponse'
        410:
          description: El pedido fue anulado.
          schema:
            $ref: '#/definitions/OrderCanceled'
        404:
          description: error obtención de datos   
          
  /pdp/order/{order_id}/transfers:
    post:
      tags:
      - transferencia
      summary: Generar Transferencia  ***(Público)***
      description: |
        Configurar pago por transferencia en transferencia.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: path
          name : order_id
          type: integer
          required: true
          description: Id de orden
        - in: body
          required: true
          name: body
          description: parametros para generar una transferencia
          schema:
            $ref: '#/definitions/transfersInit'
      responses:
        201:
          description: ok
          schema:
            $ref: '#/definitions/transfersResponse'
        400:
          description: Parametros de entrada incorrectos
          schema:
            $ref: '#/definitions/ErrorResponse'
        410:
          description: El pedido fue anulado.
          schema:
            $ref: '#/definitions/OrderCanceled'
        404:
          description: error obtención de datos  
  /pdp/general/paymentmethods:
    get:
      tags:
      - general
      summary: Obtener lista de medios de pago  ***(Público)***
      description: |
        Setear pago por cupón.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: path
          name: order_id
          description: id de orden de boton de pago
          required: true
          type: number
      responses:
        200:
          description: ok
          schema:
            type: array
            items:
              $ref: '#/definitions/paymentMethod'  
        410:
          description: El pedido fue anulado.
          schema:
            $ref: '#/definitions/OrderCanceled'
  /pdp/general/params/{param}:
    get:
      tags:
      - general
      summary: Obtener el parametro ***(Interno)*** 
      description: |
        Obtener parametros de la plataforma. 
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: path
          name: param
          description: nombre del parametro
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/parameter'
  /pdp/poll/{pool_id}:
    get:
      tags:
      - encuesta
      summary: Obtener lista de respuestas de una encuesta  ***(Público)***
      description: |
        Este servicio permite obtener la lista de respuestas de una encuesta.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: path
          name: pool_id
          description: ID de encuesta
          required: true
          type: "integer"
      responses:
        200:
          description: ok
          schema:
            type: array
            items:
              $ref: '#/definitions/pollAnswer'
        400:
          description: Parametros de entrada incorrectos
          schema:
            $ref: '#/definitions/ErrorResponse'
        404:
          description: error al obtener la liesta de respuestas   
    post:
      tags:
      - encuesta
      summary: Responde encuesta con el id de respuesta seleccionado  ***(Público)***
      description: |
        Este servicio permite responder la encuesta.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: path
          name: pool_id
          description: ID de encuesta
          required: true
          type: "integer"
        - in: body
          required: true
          name: body
          description: |
            El body debe contener 
              * order_id : ID del pedido
              * answer_id : ID de respuesta
              * other_answer : Other Answer
          schema:
            $ref: '#/definitions/poolObject'
      responses:
        200:
          description: ok
        400:
          description: Parametros de entrada incorrectos
          schema:
            $ref: '#/definitions/ErrorResponse'
        404:
          description: El error al obtener la encuesta   
        
  
definitions:

  parameter:
    type: object
    required:
      - id
      - value
    description: Parámetro básico **(Response)**
    properties:
      value:
        type: string
        description: descripción del parámetro
        
  orderInput:
    type: object
    required:
    - ec_order_id
    - total_amount
    - general_description
    - payment_method
    properties:
      ec_order_id:
        type: string
        example: "ERWER213"
      user_data: 
        $ref: '#/definitions/userData'
      total_amount:
        type: number
        example: 40000
      type_amount:
        type: string
        example: "CLP"
      general_description:
        type: string
        example: Esta es una orden
      payment_method:
        type: number
        example: 2
      urls:
        $ref: '#/definitions/urlObject'
  
  orderUpdate:
    type: object
    properties:
      ec_order_id:
        type: string
        example: "ERWER213"
      general_description:
        type: string
        example: Esta es una orden
      payment_method:
        type: number
        example: 2
      user_data: 
        $ref: '#/definitions/userData'
        
  userData: 
    type: object
    properties:
      email:
          type: string
          example: "developer@email.cl"
      rut:
        type: string
        example: "1-9"

 
  cashInit:
    type: object
    required:
    - order_id
    properties:
      order_id:
        type: integer
        example: 1111111111
        
  pollAnswer:
    type: object
    required:
    - order_id
    - user_id
    - user_email
    properties:
      answer_id:
        type: integer
        example: 1111111111
      text_answer:
        type: string
        example: 152
  

  paymentMethod:
    type: object
    required:
      - id
      - value
    description: Parámetro básico **(Response)**
    properties:
      id:
        type: integer
        description: identificador del metodo de pago
        example: 1
      code:
        type: string
        description: Código del metodo de pago
        example: 15564
      name:
        type: string
        description: Nombre del metodo de pago
        example: "efectivo"
      description:
        type: string
        description: Descripcion del metodo de pago
        example: "Pago con cupon en comercio multicaja"
      anonymous_payment:
        type: string
        description: Descripcion del meodo de pago
        example: "Pago con cupon en comercio multicaja"
      max_amount:
        type: string
        description: Monto maximo de pago
        example: "Monto maximo aceptado en el medio de pago"
      enabled:
        type: boolean
        description: Estado del medio de pago
        example: true
  
  transfersInit:
    type: object
    required:
    - id
    - user_id
    - id_person_app
    - slp
    properties:
      order_id:
        type: integer
        example: 1
  
  transfersResponse:
    type: object
    required:
    - id_trx
    - user_new_slp
    - tef_status
    - tef_id
    - tef_amount
    - tef_expires
    - tef_now
    - tef_uses_slp
    - tef_amount_slp
    - account_name
    - account_rut
    - account_email
    - account_bank
    - account_type
    - account_number
    - account_new
    properties:
      id_trx:
        type: string
        example: 1
      user_new_slp:
        type: number
        example: 1
      tef_status:
        type: string
        example: 1
      tef_id:
        type: integer
        example: 1
      tef_amount:
        type: integer
        example: 1
      tef_expires:
        type: string
        format: date-time
        example: "2018-01-14T15:27:42.669Z"
      tef_now:
        type: string
        format: date-time
        example: "2018-01-14T15:27:42.669Z"
      tef_uses_slp:
        type: boolean
        example: true
      tef_amount_slp:
        type: number
        example: 1000
      account_name:
        type: string
        example: mario
      account_rut:
        type: string
        example: 1-9
      account_email:
        type: string
        example: email@email.cl
      account_bank:
        type: string
        example: El de los pobres
      account_type:
        type: string
        example: de papel confort
      account_number:
        type: string
        example: 0000000655712
      account_new:
        type: integer
        example: 1
          
  orderStatus:
    required:
    - order_status
    - description
    - ec_order_id
    - payment_method
    properties:
      order_id:
        type: integer
        example: 455665
      order_status:
        type: integer
        example: 2
      description:
        type: string
        example:  EXPIRED
      user_data: 
        $ref: '#/definitions/userData'
      ec_order_id:
        type: string
        example: "EH32434"
      ecommerce_id:
        type: string
        example: "EH32434"
      total_amount:
        type: integer
        example: 60000
      payment_info:
        $ref: '#/definitions/paramPaymentMethod'
      urls:
        $ref: '#/definitions/urlObject'
  
  urlObject:
    required:
      - url_notify 
    properties:
      url_notify:
          type: string
          example: "http://multicaja.cl/notify"
      url_goback:
          type: string
          example: "http://multicaja.cl/goback"
  
  
        
  paramPaymentMethod:
    type: object
    required:
    - payment_method
    - payment_date
    - payment_user
    - payment_authorization
    - payment_amount
    - payment_date_expiration
    - payment_date_created
    - payment_canceled
    properties:
      payment_method:
        type: string
        example: Efectivo Multicaja
      payment_date:
        type: string
        example: "2018-01-14T15:27:42.669Z"
      payment_amount:
        type: number
        example: 40000
      payment_date_expiration:
        type: string
        example: "2018-01-14T15:27:42.669Z"
      payment_date_update:
        type: string
        example: "2018-01-14T15:27:42.669Z"
      payment_date_created:
        type: string
        example: "2018-01-14T15:27:42.669Z"
      payment_canceled:
        type: boolean
        example: false
        
  
        
  ErrorResponse:
    type: object
    properties:
      status: 
        type: integer
        format: int32
        example: 400
        description: Código HTTP
      error: 
        type: string
        example: Bad Request
        description: Nombre del código HTTP
      message:
        type: string
        example: Invalid property '{property_name}'.
        description: Descripción del error
      path:
        type: string
        example: "/pdp/{path}"
        description: Url de la solicitud http
      timestamp:
        type: string
        format: date-time
        example: "2018-03-16T16:38:31.28571"
        description: Fecha y hora del error
  
  OrderCanceled:
    type: object
    properties:
      status: 
        type: integer
        format: int32
        example: 403
        description: Código HTTP
      error: 
        type: string
        example: Order canceled
        description: Nombre del código HTTP
      message:
        type: string
        example: La orden N° '{order_id}' fue anulada.
        description: Descripción del error
      path:
        type: string
        example: "/pdp/{path}"
        description: Url de la solicitud http
      timestamp:
        type: string
        format: date-time
        example: "2018-03-16T16:38:31.28571"
        description: Fecha y hora del error
  
  poolObject:
    properties:
      order_id: 
        type: integer
        example: 5643
        description: ID de pedido
      user_id: 
        type: integer
        example: 445
        description: ID del usuario que responde la encuesta
      answer_id: 
        type: integer
        example: 4554
        description: ID de la respuesta
      other_answer:
        type: string
        example: "Texto de respuesta opcional"
        description: Respuesta opcional
        
      
    
