swagger: '2.0'
info:
  description: |
    Bienvenido a la API de [Multicaja](https://www.multicaja.cl) (Alpha)
    Definición de Helpers
    ** Este es un proyecto alpha y por lo tanto sufrirá muchos cambios **

    Todos los requests son autenticados usando un `api-key`.

    Existen dos ambientes: `qa` y `producción`. El `host` de `qa` es `apiqa.multicaja.cl`.
  version: '0.5'
  title: API Multicaja (Alpha)
host: 'api.multicaja.cl'
basePath: /v0.1-alpha/
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: parámetros
    description: Listas de parámetros inmutables
paths:
  /helpers/banks:
    get:
      summary: Lista bancos
      tags: 
        - parámetros
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Helper'
  /helpers/communes:
    get:
      summary: Lista comunas
      tags: 
        - parámetros
      parameters:
        - name: "region"
          in: "query"
          description: "id de region para busqueda"
          required: false
          type: "integer"
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Helper'
  /helpers/regions:
    get:
      summary: Lista regiones
      tags: 
        - parámetros
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Helper'
  /helpers/commercial_activity:
    get:
      summary: Lista giros comerciales
      tags: 
        - parámetros
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Helper'
definitions:
  Helper:
    type: object
    required:
      - id
      - value
    description: Parámetro básico **(Response)**
    properties:
      id:
        type: integer
        description: identificador del parámetro
      value:
        type: string
        description: nombre del parámetro
      desc:
        type: string
        description: descripción del parámetro
  ErrorObj:
    type: object
    description: Error que devuelve la api ante un `HTTP 422` **(Response)**
    required:
      - code
    properties:
      code:
        type: integer
        format: int32
        description: Código que representa el error. No será igual al código HTTP.
        example: 1024
      message:
        type: string
        description: Descripción corta del error
        example: "El cliente no pasó la validación"
      details:
        type: array
        items:
          $ref: '#/definitions/ErrorObjDetail'
  ErrorObjDetail:
    type: object
    description: |
      Cuando un error está compuesto por una lista de sub-errores, vendrán en este objeto
      Componente de `ErrorObj`
      
      **No se usa de manera independiente en la API**
    properties:
      code:
        type: integer
        format: int32
        description: Código que representa el sub-error
        example: 227
      message:
        type: string
        description: Descripción del sub-error
        example: "El nombre no puede estar vacío"
