swagger: '2.0'
info:
  description: |
    
    ## Limitaciones
    - Sólo tarjetas de crédito Mastercard
    - Sin cuotas
    - Sin captura diferida
    - Todos los montos deben estar en pesos chilenos (ISO 4217 = CLP)
    - La API no soporta CORS
    
    ## Reglas de la API
    - El campo `consumer_transaction_id` **debe** ser único (incluso en días y transacciones distintas).
    - Todos los requerimientos deben ser realizados sobre *HTTPS*. Los requerimientos sobre *HTTP* fallarán.
    - Todos los requerimientos son autenticados. Debe incluir el encabezado `Api-Key: <key>`.
    
    ## Idempotencia
    La API soporta *idempotencia*, por lo tanto puedes reintentar un requerimiento sin peligro de que el recurso se cree dos veces. Para esto debes incluir el encabezado `Idempotency-Key: <key>`, donde `key` es un identificador único de tu sistema o UUID. La clave tiene una validez de 24 horas.
    
    - NOTA: Si envías dos requerimientos con igual `consumer_transaction_id` y distinto `Idempotency-Key`, se entendrán como dos requerimientos **diferentes** y uno de ellos fallará dado que el campo `consumer_transaction_id` debe ser único.
    
    
    
  version: '0.1'
  title: API Pagos con tarjeta
  
host: 'api.multicaja.cl'
basePath: /card-payments/v0.1/
consumes:
  - application/json
produces:
  - application/json
paths:

  /charges:
    post:
      summary: Venta con tarjeta
      description: |
        Realiza un cargo en una tarjeta de crédito.
      parameters:
        - in: body
          name: charge_new
          description: Venta con tarjeta
          required: true
          schema:
            $ref: '#/definitions/charge_new'
      responses:
        '200':
          description: |
            OK - Venta exitosa
          schema:
            $ref: '#/definitions/charge'
        '400':
          description: Error en parámetros, se lanza a cuando un parámetro es requerido y no se ha enviado
          schema:
            $ref: '#/definitions/error_obj'
        '401':
          description: API Key no autorizada
          schema:
            $ref: '#/definitions/error_obj'
        '402':
          description: Transacción se intentó, pero falló.
          schema:
            $ref: '#/definitions/error_obj'
        '500':
          description: Error indeterminado, se lanza cuando ocurre un error imprevisto de sistema
          schema:
            $ref: '#/definitions/error_obj'
  /reversals:
    post:
      summary: Reversa de una venta o devolución
      description: |
        Reversa una transacción previamente autorizada
        
      parameters:
        - in: body
          name: reversal_new
          description: Reversa de venta con tarjeta
          required: true
          schema:
            $ref: '#/definitions/reversal_new'
      responses:
        '200':
          description: |
            OK - Reversa exitosa
          schema:
            $ref: '#/definitions/reversal'
        '400':
          description: Error en parámetros, se lanza a cuando un parámetro es requerido y no se ha enviado
          schema:
            $ref: '#/definitions/error_obj'
        '401':
          description: API Key no autorizada
          schema:
            $ref: '#/definitions/error_obj'
        '500':
          description: Error indeterminado, se lanza cuando ocurre un error imprevisto de sistema
          schema:
            $ref: '#/definitions/error_obj'
  /refunds:
    post:
      summary: Devolución de un cargo realizado a una tarjeta
      description: |
        Devuelve total o parcialmante un cargo realizado a una tarjeta de crédito.
        
        ## Devolución total
        - El objeto `amount` es opcional. En caso que se envíe, el campo `value` debe corresponder al monto total del cargo.
        
        ## Devolución parcial
        - El objeto `amount` corresponde al monto que se quiere devolver. Debe ser mayor que cero y menor o igual al monto no devuelto de la venta.
        - Puedes realizar hasta **10 devoluciones parciales** asociadas a la misma venta.
        
      parameters:
        - in: body
          name: refund_new
          description: Devolución de cargo
          schema:
            $ref: '#/definitions/refund_new'
      responses:
        '200':
          description: |
            OK - devolución exitosa
          schema:
            $ref: '#/definitions/refund'
        '400':
          description: Error en parámetros, se lanza a cuando un parámetro es requerido y no se ha enviado
          schema:
            $ref: '#/definitions/error_obj'
        '401':
          description: API Key no autorizada
          schema:
            $ref: '#/definitions/error_obj'
        '500':
          description: Error indeterminado, se lanza cuando ocurre un error imprevisto de sistema
          schema:
            $ref: '#/definitions/error_obj'
            
  
definitions:

  refund_new:
    type: object
    description: |
      Solicitud de devolución **(Request)**
    required:
      - original_consumer_transaction_id
      - consumer_transaction_id
    properties:
      consumer_transaction_id:
        type: string
        description: Identificador único de la transacción generado por el consumidor de la API
        example: "xhGXSPKviU83lln_xc9lc"
      original_consumer_transaction_id:  
        type: string
        description: Identificador de la venta original, sobre la que se realizará la devolución.
        example: "crlfUYEBK14zotCTykezJkfg"
      amount:
        $ref: "#/definitions/amount_and_currency_new"
      additional_data:
        $ref: "#/definitions/addtitional_data"  
    
  refund:
    type: object
    description: |
      Solicitud de devolución **(Response)**
    required:
      - consumer_transaction_id
    properties:
      consumer_transaction_id:
        type: string
        description: Identificador único de la transacción generado por el consumidor de la API
        example: "xhGXSPKviU83lln_xc9lc"
      amount:
        $ref: '#/definitions/amount_and_currency_new'
      id:
        type: integer
        description: Identificador único de la devolución generado por Multicaja
        example: 7654320
      external_authorization_code:
        type: integer
        description: Identificador único de la transacción en el switch de la bandera
        example: 1231232
      timestamps:
        $ref: '#/definitions/timestamps'
        
  reversal_new:
    type: object
    description: |
      Solicitud de reversa de una transacción **(Request)**
    required:
      - consumer_transaction_id
    properties:
      consumer_transaction_id:
        type: string
        description: Identificador único de la transacción que se quiere reversar.
        example: "crlfUYEBK14zotCTykezJkfg"
        
  reversal:
    type: object
    description: |
      Respuesta a solicitud de reversa de una transacción **(Response)**
    allOf:
      - $ref: "#/definitions/reversal_new"
      - type: object
        required:
          - status
        properties:
          status: 
            type: string
            description: Estado de la reversa.
            example: "approved"      
          timestamps:
            $ref: '#/definitions/timestamps'


  charge_base:
    type: object
    description: |
      Contenido mínimo de una venta con tarjeta
    properties:
      consumer_transaction_id:
        type: string
        description: Identificador único de la transacción generado por el consumidor de la API
        example: "crlfUYEBK14zotCTykezJkfg"
      amount:
        $ref: "#/definitions/amount_and_currency_new"
        
  charge_new:
    type: object
    description: |
      Solicitud de venta **(Request)**
    allOf:
      - $ref: "#/definitions/charge_base"
      - type: object
        required:
          - card
          - amount
          - consumer_transaction_id
          - merchant_code
        properties:
          card:
            $ref: "#/definitions/card_new"
          merchant_code:
            type: string
            description: Código de comercio asociado a la compra
            example: "0023434"
          soft_descriptor:
            type: string
            description: Nombre del comercio. Máximo 6 caracteres.
            example: "STORE-001"
          additional_data:
            $ref: "#/definitions/addtitional_data"

  charge:
    type: object
    description: |
      Respuesta a solicitud de venta **(Response)**
    allOf:
      - $ref: "#/definitions/charge_base"
      - type: object
        required:
          - id
          - external_authorization_code
          - process_date
          - timestamps
        properties:
          id:
            type: integer
            description: Código identificador de la compra en los sistemas de Multicaja
            example: 7783834
          external_authorization_code:
            type: integer
            description: Identificador único de la transacción en el switch de la bandera
            example: 1231232
          timestamps:
            $ref: '#/definitions/timestamps'
            
  timestamps:
    type: object
    description: |
      Fecha de creación y de última modificación **(Response)**
    properties:
      created_at:
        type: string
        format: date-time
        example: "2018-01-14T15:27:42.669Z"
      updated_at:
        type: string
        format: date-time
        example: "2018-03-02T10:03:12.123Z"

  amount_and_currency_new:
    type: object
    description: Monto en una moneda específica
    required:
      - currency_code
      - value
    properties:
      value:
        type: number
        description: Monto en formato decimal
        example: "1000.00"
      currency_code:
        type: string
        description: Código ISO 4217 de la moneda
        example: "CLP"
        
  error_obj:
    type: object
    description: Error
    required:
      - code
    properties:
      code:
        type: string
        description: Código que representa el error. No será igual al código HTTP.
        example: "INSUFFICIENT_FUNDS"
      message:
        type: string
        description: Descripción corta del error
        example: "La tarjeta no tiene saldo"

  card_new:
    type: object
    description: |
      Información de la tarjeta de crédito
    required:
      - exp_month
      - exp_year
      - pan
    properties:
      pan:
        type: string
        description: PAN de la tarjeta
        example: "5144611670946763"
      exp_month:
        type: integer
        description: mes de expiración
        example: 9
      exp_year:
        type: integer
        description: año de expiración
        example: 2020
      cvc:
        type: integer
        description: código de seguridad
        example: 123
      name_on_card:
        type: string
        description: Nombre impreso en la tarjeta
        example: "Pedro Perez"
  addtitional_data:
    type: object
    description: |
      Objeto JSON con atributos adicionales para la transacción.
